## -*- coding: utf-8 -*-
#"""opencv_scoreboard.ipynb
#
#Automatically generated by Colaboratory.
#
#Original file is located at
#    https://colab.research.google.com/drive/1rT7x8gcf8XIWaWxOLseYCi8UucFJMhdv
#"""
import utils
import cv2
import numpy as np
import time



#cute_img = cv2.imread("cute_no_background.png")
#small = cv2.resize(cute_img, (0,0), fx=0.2, fy=0.2)
#
#i=0
#delay=0.25
#while True:
#    img = np.zeros((512,512,3), np.uint8)
#    cv2.putText(img, 'Welcome to', (150, 100), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA);
#    cv2.putText(img, 'SHADOW FIGHTER!', (30, 200), cv2.FONT_HERSHEY_TRIPLEX, 1.5, (0, 0, 255), 5, cv2.LINE_AA);
#    y_offset=230
#    x_offset=130
#    img[y_offset:y_offset+small.shape[0], x_offset:x_offset+small.shape[1]] = small
#    cv2.imshow('',img)
#    if cv2.waitKey(1) & 0xff == ord('\r'):
#        print('ahhh')
##        cv2.destroyAllWindows()
#        break
#    time.sleep(delay)
#    
#    cv2.putText(img, 'Press enter to start', (100, 450), cv2.FONT_HERSHEY_COMPLEX, 0.8, (0, 0, 255), 2, cv2.LINE_AA);
#    cv2.imshow('',img)
#    if cv2.waitKey(1) & 0xff == ord('\r'):
#        print('ahhh')
##        cv2.destroyAllWindows()
#        break
#    time.sleep(delay)
#
#    
#    img = np.zeros((512,512,3), np.uint8)
#    cv2.putText(img, 'Welcome to', (150, 100), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA);
#    cv2.putText(img, 'SHADOW FIGHTER!', (30, 200), cv2.FONT_HERSHEY_TRIPLEX, 1.5, (0, 0, 255), 5, cv2.LINE_AA);
#    y_offset=230
#    x_offset=130
#    img[y_offset:y_offset+small.shape[0], x_offset:x_offset+small.shape[1]] = small
#    cv2.imshow('',img)
#    if cv2.waitKey(1) & 0xff == ord('\r'):
#        print('ahhh')
##        cv2.destroyAllWindows()
#        break
#    time.sleep(delay)
#    
#
#    
##
##while True:
##  ch = cv2.waitKey(10)
##  print(ch)
##  if ch == 27:
##    cv2.destroyAllWindows()
##    break
#
#img2 = np.zeros((512,512,3), np.uint8)
#cv2.putText(img2, '3', (160, 300), cv2.FONT_HERSHEY_TRIPLEX, 8, (0, 0, 255), 4, cv2.LINE_AA);
#cv2.imshow('',img2)
#cv2.waitKey(1)
##
#img2 = np.zeros((512,512,3), np.uint8)
#cv2.putText(img2, '2', (160, 300), cv2.FONT_HERSHEY_TRIPLEX, 8, (0, 0, 255), 4, cv2.LINE_AA);
#cv2.imshow('',img2)
#time.sleep(1)
#cv2.waitKey(1)
#
#img2 = np.zeros((512,512,3), np.uint8)
#cv2.putText(img2, '1', (160, 300), cv2.FONT_HERSHEY_TRIPLEX, 8, (0, 0, 255), 4, cv2.LINE_AA);
#cv2.imshow('',img2)
#time.sleep(1)
#cv2.waitKey(1)
##
#img2 = np.zeros((512,512,3), np.uint8)
#cv2.putText(img2, 'FIGHT!', (40, 300), cv2.FONT_HERSHEY_TRIPLEX, 4, (0, 0, 255), 4, cv2.LINE_AA);
#time.sleep(1)
#cv2.imshow('',img2)
#cv2.waitKey(1)
#time.sleep(1)
#cv2.destroyAllWindows()


h=600
w=800
xadj=150
yadj=30
delay=0.25



utils.start_screen(h,w,xadj,yadj,delay)



start_screen(h,w,xadj,yadj,delay)
